apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: myapp-use2-infrastructure
  namespace: myapp-use2-argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project with infrastructure related applications
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
