{{- if .Values.awsLoadBalancerController.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix | default "" }}{{ .Values.awsLoadBalancerController.name }}{{ .Values.nameSuffix | default "" }}
  namespace: {{ .Values.awsLoadBalancerController.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.awsLoadBalancerController.project }}
  destination:
    server: {{ .Values.awsLoadBalancerController.destination.server }}
    namespace: {{ .Values.awsLoadBalancerController.destination.namespace }}
  source:
    path: {{ .Values.awsLoadBalancerController.source.path }}
    repoURL: {{ .Values.awsLoadBalancerController.source.repoURL }}
    targetRevision: {{ .Values.awsLoadBalancerController.source.targetRevision }}
    chart: {{ .Values.awsLoadBalancerController.source.chart }}
    {{- if and .Values.awsLoadBalancerController.source.helm (not (empty .Values.awsLoadBalancerController.source.helm.valuesObject)) }}
    helm:
      valuesObject: {{ toYaml .Values.awsLoadBalancerController.source.helm.valuesObject | nindent 8 }}
    {{- end }}
  {{- if and .Values.awsLoadBalancerController.syncPolicy (not (empty .Values.awsLoadBalancerController.syncPolicy)) }}
  syncPolicy:
{{ toYaml .Values.awsLoadBalancerController.syncPolicy | indent 4 }}
  {{- end }}
{{- end }}
