{{- if and .Values.awsLoadBalancerController.enabled .Values.awsLoadBalancerController.ingresses }}
{{- range $index, $ingress := .Values.awsLoadBalancerController.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.namePrefix | default "" }}{{ $ingress.name }}{{ $.Values.nameSuffix | default "" }}
  namespace: {{ $ingress.namespace }}
  annotations:
    {{- range $key, $value := $ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: alb
  rules:
    {{- range $rule := $ingress.rules }}
    - http:
        paths:
          {{- range $path := $rule.http.paths }}
          - pathType: {{ $path.pathType }}
            path: {{ $path.path }}
            backend:
              service:
                name: {{ $path.backend.service.name }}
                port:
                  name: {{ $path.backend.service.port.name }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}

