global:
  defaultStorageClass: "efs-sc"
image:
  tag: 7.2.4-debian-12-r16
architecture: replication
master:
  count: 1
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 1
      memory: 512Mi
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]
  nodeSelector:
    myApp: "myApp"
  persistence:
    enabled: true
    storageClass: efs-sc

replica:
  kind: StatefulSet
  replicaCount: 2
  resources:
    requests:
      cpu: 0.5
      memory: 512Mi
    limits:
      cpu: 1
      memory: 512Mi
  podSecurityContext:
    enabled: true
    fsGroupChangePolicy: Always
    sysctls: []
    supplementalGroups: []
    fsGroup: 1001
  containerSecurityContext:
    enabled: true
    seLinuxOptions: {}
    runAsUser: 1001
    runAsGroup: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ["ALL"]
  nodeSelector:
    myApp: "myApp"
  persistence:
    enabled: true
    storageClass: efs-sc
  autoscaling:
    enabled: false
auth:
  existingSecret: myapp-redis-secrets-use2
