clusterOperator:
  nodeSelector:
    C8App: "C8App"

extraDeploy:
  - apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    metadata:
      name: myapp-rabbitmq-cluster-use2
      namespace: myapp-rabbitmq-use2
    spec:
      replicas: 2
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: "1"
          memory: 2Gi
      persistence:
        storageClassName: efs-sc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: C8App
                    operator: In
                    values:
                      - C8App
      image: bitnami/rabbitmq:3.11-debian-11
      service:
        type: ClusterIP
      rabbitmq:
        additionalConfig: |
          log.console.level = debug
          channel_max = 1700
          cluster_partition_handling = pause_minority
          vm_memory_high_watermark_paging_ratio = 0.99
          disk_free_limit.relative = 1.0
          collect_statistics_interval = 10000

  - apiVersion: rabbitmq.com/v1beta1
    kind: Policy
    metadata:
      name: myapp-rabbitmq-cluster-use2
      namespace: myapp-rabbitmq-use2
    spec:
      name: myapp-rabbitmq-cluster-use2
      applyTo: "all"
      pattern: ""
      definition:
        ha-mode: all
        ha-sync-mode: automatic
      rabbitmqClusterReference:
        name: myapp-rabbitmq-cluster-use2

  - apiVersion: rabbitmq.com/v1beta1
    kind: User
    metadata:
      name: c8
      namespace: myapp-rabbitmq-use2
    spec:
      tags:
        - administrator
      rabbitmqClusterReference:
        name: myapp-rabbitmq-cluster-use2
      importCredentialsSecret:
        name: myapp-redis-secrets-use2

  - apiVersion: rabbitmq.com/v1beta1
    kind: Permission
    metadata:
      name: myapp-rabbitmq-cluster-permission-use2
      namespace: myapp-rabbitmq-use2
    spec:
      vhost: "/"
      user: "c8" # name of the RabbitMQ user
      permissions:
        write: ".*"
        configure: ".*"
        read: ".*"
      rabbitmqClusterReference:
        name: myapp-rabbitmq-cluster-use2
