{{- if .Values.kubePrometheusStack.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix | default "" }}{{ .Values.kubePrometheusStack.name }}{{ .Values.nameSuffix | default "" }}
  namespace: {{ .Values.kubePrometheusStack.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.kubePrometheusStack.project }}
  destination:
    server: {{ .Values.kubePrometheusStack.destination.server }}
    namespace: {{ .Values.kubePrometheusStack.destination.namespace }}
  sources:
  {{- range .Values.kubePrometheusStack.sources }}
  - repoURL: {{ .repoURL }}
    {{- if .targetRevision }}
    targetRevision: {{ .targetRevision }}
    {{- end }}
    {{- if .path }}
    path: {{ .path }}
    {{- end }}
    {{- if .chart }}
    chart: {{ .chart }}
    {{- end }}
    {{- if .helm }}
    helm:
      {{- if .helm.valuesObject }}
      valuesObject: {{ toYaml .helm.valuesObject | nindent 8 }}
      {{- end }}
      {{- if .helm.valueFiles }}
      valueFiles:
      {{- range .helm.valueFiles }}
        - {{ . }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .ref }}
    ref: {{ .ref }}
    {{- end }}
  {{- end }}
  {{- if and .Values.kubePrometheusStack.syncPolicy (not (empty .Values.kubePrometheusStack.syncPolicy)) }}
  syncPolicy:
{{ toYaml .Values.kubePrometheusStack.syncPolicy | indent 4 }}
  {{- end }}
{{- end }}
