loki:
  replicas: 1

  ingress:
    enabled: false
    ingressClassName: myapp-use2-ingress-nginx
    hosts:
      - host: loki.myapp.configure8.io
        paths: ["/"]

  nodeSelector:
    myApp: "myApp"

  resources:
    limits:
      cpu: 2500m
      memory: 4096Mi
    requests:
      cpu: 1000m
      memory: 4096Mi

  # affinity:
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #     - labelSelector:
  #         matchExpressions:
  #         - key: app
  #           operator: In
  #           values:
  #           - loki
  #       topologyKey: topology.kubernetes.io/zone

  persistence:
    enabled: true
    accessModes:
      - ReadWriteMany
    storageClassName: efs-sc

  serviceAccount:
    create: true
    name: "myapp-loki-use2"
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789123:role/my-myapp-prod-loki-logs-role"

  # https://grafana.com/docs/loki/latest/configuration/#configuring-grafana-loki
  config:
    server:
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600

    # https://grafana.com/docs/loki/latest/operations/storage/wal/
    auth_enabled: false

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_query_parallelism: 64
      max_streams_per_user: 500000
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 24
      max_concurrent_tail_requests: 20
      retention_period: 30d
      per_stream_rate_limit: 16MB
      per_stream_rate_limit_burst: 64MB
      split_queries_by_interval: 0 # 2h

    compactor:
      shared_store: s3
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      working_directory: /data/loki/boltdb-shipper-compactor
    # https://github.com/grafana/loki/blob/main/docs/sources/storage/_index.md#schema-configs
    # https://grafana.com/docs/loki/latest/operations/storage/schema/
    schema_config:
      configs:
        - from: 2022-10-29
          # https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      aws:
        s3: s3://us-east-2/123456789123-myapp-loki-logs
        s3forcepathstyle: true
        bucketnames: 123456789123-myapp-loki-logs
        region: us-east-2
        insecure: false
        sse_encryption: false
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: s3

promtail:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
  config:
    snippets:
      extraRelabelConfigs:
        - action: replace
          source_labels:
            - __meta_kubernetes_pod_label_myapp
          target_label: myapp
grafana:
  enabled: false
