{{- if .Values.awsEfsCsiDriver.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix | default "" }}{{ .Values.awsEfsCsiDriver.name }}{{ .Values.nameSuffix | default "" }}
  namespace: {{ .Values.awsEfsCsiDriver.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.awsEfsCsiDriver.project }}
  destination:
    server: {{ .Values.awsEfsCsiDriver.destination.server }}
    namespace: {{ .Values.awsEfsCsiDriver.destination.namespace }}
  source:
    path: {{ .Values.awsEfsCsiDriver.source.path }}
    repoURL: {{ .Values.awsEfsCsiDriver.source.repoURL }}
    targetRevision: {{ .Values.awsEfsCsiDriver.source.targetRevision }}
    chart: {{ .Values.awsEfsCsiDriver.source.chart }}
    {{- if and .Values.awsEfsCsiDriver.source.helm (not (empty .Values.awsEfsCsiDriver.source.helm.valuesObject)) }}
    helm:
      valuesObject: {{ toYaml .Values.awsEfsCsiDriver.source.helm.valuesObject | nindent 8 }}
    {{- end }}
  {{- if and .Values.awsEfsCsiDriver.syncPolicy (not (empty .Values.awsEfsCsiDriver.syncPolicy)) }}
  syncPolicy:
{{ toYaml .Values.awsEfsCsiDriver.syncPolicy | indent 4 }}
  {{- end }}
{{- end }}
