controller:
  serviceAccount:
    create: true
    name: myapp-use2-efs
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::123456789123:role/my-myapp-prod-efs-role
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi

replicaCount: 1
nodeSelector:
  myApp: "myApp"

storageClasses:
  - name: efs-sc
    provisioner: efs.csi.aws.com
    mountOptions:
      - tls
    parameters:
      provisioningMode: efs-ap
      fileSystemId: fs-0fbecb095672982a4
      directoryPerms: "700"
      gidRangeStart: "1000"
      gidRangeEnd: "2000"
      basePath: "/dynamic_provisioning"
