{{- range .Values.roles }}
  {{- if eq .type "ClusterRole" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $.namePrefix | default "" }}{{ .name }}{{ $.nameSuffix | default "" }}
rules:
{{- range .rules }}
- apiGroups:
  {{- toYaml .apiGroups | nindent 2 }}
  resources:
  {{- toYaml .resources | nindent 2 }}
  verbs:
  {{- toYaml .verbs | nindent 2 }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .name }}-binding
subjects:
- kind: Group
  name: {{ .roleBindingGroup }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
{{- end }}
