{{- range .Values.roles }}
  {{- if eq .type "Role" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $.namePrefix | default "" }}{{ .name }}{{ $.nameSuffix | default "" }}
  namespace: {{ .namespace }}
rules:
{{- range .rules }}
- apiGroups:
  {{- toYaml .apiGroups | nindent 2 }}
  resources:
  {{- toYaml .resources | nindent 2 }}
  verbs:
  {{- toYaml .verbs | nindent 2 }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-binding
  namespace: {{ .bindingNamespace }}
subjects:
- kind: Group
  name: {{ .roleBindingGroup }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ .name }}
  apiGroup: rbac.authorization.k8s.io
  {{- end }}
{{- end }}
