{{- if .Values.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.namePrefix | default "" }}{{ .Values.externalSecrets.name }}{{ .Values.nameSuffix | default "" }}
  namespace: {{ .Values.externalSecrets.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.externalSecrets.project }}
  destination:
    server: {{ .Values.externalSecrets.destination.server }}
    namespace: {{ .Values.externalSecrets.destination.namespace }}
  sources:
  {{- range .Values.externalSecrets.sources }}
  - repoURL: {{ .repoURL }}
    {{- if .targetRevision }}
    targetRevision: {{ .targetRevision }}
    {{- end }}
    {{- if .path }}
    path: {{ .path }}
    {{- end }}
    {{- if .chart }}
    chart: {{ .chart }}
    {{- end }}
    {{- if .helm }}
    helm:
      {{- if .helm.valuesObject }}
      valuesObject: {{ toYaml .helm.valuesObject | nindent 8 }}
      {{- end }}
      {{- if .helm.valueFiles }}
      valueFiles:
      {{- range .helm.valueFiles }}
        - {{ . }}
      {{- end }}
      {{- end }}
    {{- end }}
    {{- if .ref }}
    ref: {{ .ref }}
    {{- end }}
  {{- end }}
  {{- if and .Values.externalSecrets.syncPolicy (not (empty .Values.externalSecrets.syncPolicy)) }}
  syncPolicy:
{{ toYaml .Values.externalSecrets.syncPolicy | indent 4 }}
  {{- end }}
{{- end }}
