{{- if and .Values.externalSecrets.enabled (not (empty .Values.externalSecrets.stores)) }}
{{- range .Values.externalSecrets.stores }}
---
apiVersion: external-secrets.io/v1beta1
kind: {{ .kind }}
metadata:
  name: {{ .name }}
  {{- if eq .kind "SecretStore" }}
  namespace: {{ .namespace }}
  {{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  provider:
    aws:
      service: {{ .provider.aws.service }}
      region: {{ .provider.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .provider.aws.auth.jwt.serviceAccountRef.name }}
            namespace: {{ .provider.aws.auth.jwt.serviceAccountRef.namespace }}
{{- end }}
{{- end }}
