autoDiscovery:
  clusterName: "my-eks-cluster-myapp-use2"
replicaCount: 2
awsRegion: us-east-2
resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 30m
    memory: 300Mi
rbac:
  create: true
  serviceAccount:
    name: myapp-use2-cluster-autoscaler
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::123456789123:role/my-myapp-prod-cluster-autoscaler-role"
nodeSelector:
  myApp: "myApp"
